// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMi_TAm7teaM3PS3Sf9etiTIcTaZRnprQ',
    appId: '1:469343748655:web:4920940ac6dae88d85fcda',
    messagingSenderId: '469343748655',
    projectId: 'ecomapp-17c26',
    authDomain: 'ecomapp-17c26.firebaseapp.com',
    storageBucket: 'ecomapp-17c26.appspot.com',
    measurementId: 'G-T12KVNCRCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6y6XWj50JzvPo7-OUfgqNBTRdz3fiju0',
    appId: '1:469343748655:android:1d011d9061063dcd85fcda',
    messagingSenderId: '469343748655',
    projectId: 'ecomapp-17c26',
    storageBucket: 'ecomapp-17c26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABeYp_WdlZlViUOsDWPXGsDyXGeeiDsoY',
    appId: '1:469343748655:ios:2415b9b9e280d46485fcda',
    messagingSenderId: '469343748655',
    projectId: 'ecomapp-17c26',
    storageBucket: 'ecomapp-17c26.appspot.com',
    iosBundleId: 'com.example.vilCone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABeYp_WdlZlViUOsDWPXGsDyXGeeiDsoY',
    appId: '1:469343748655:ios:2415b9b9e280d46485fcda',
    messagingSenderId: '469343748655',
    projectId: 'ecomapp-17c26',
    storageBucket: 'ecomapp-17c26.appspot.com',
    iosBundleId: 'com.example.vilCone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMi_TAm7teaM3PS3Sf9etiTIcTaZRnprQ',
    appId: '1:469343748655:web:83ab3adb15a5333185fcda',
    messagingSenderId: '469343748655',
    projectId: 'ecomapp-17c26',
    authDomain: 'ecomapp-17c26.firebaseapp.com',
    storageBucket: 'ecomapp-17c26.appspot.com',
    measurementId: 'G-YHGWJ66JTH',
  );

}